[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#141b1e"
foreground = "#bdc3c2"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.selection]
text = "CellBackground"
cursor = "CellForeground"

[colors.normal]
black = "#232a2d"
red = "#e57474"
green = "#8ccf7e"
yellow = "#e5c76b"
blue = "#67b0e8"
magenta = "#c47fd5"
cyan = "#6cbfbf"
white = "#b3b9b8"

[colors.bright]
black = "#2d3437"
red = "#ef7e7e"
green = "#96d988"
yellow = "#f4d67a"
blue = "#71baf2"
magenta = "#ce89df"
cyan = "#67cbe7"
white = "#bdc3c2"
