[colors]
draw_bold_text_with_bright_colors = true
primary = { background = "#1c1c1c", foreground = "#ffffff" }
cursor = { text = "CellBackground", cursor = "CellForeground" }
selection = { text = "CellBackground", cursor = "CellForeground" }
[colors.normal]
black = "#000000"
red = "#cc0000"
green = "#4e9a06"
yellow = "#c4a000"
blue = "#3465a4"
magenta = "#75507b"
cyan = "#06989a"
white = "#d3d7cf"
[colors.bright]
black = "#555753"
red = "#ef2929"
green = "#90d44e"
yellow = "#ffed65"
blue = "#85c7f2"
magenta = "#f397d6"
cyan = "#34e2e2"
white = "#eeeeec"
