[colors]
draw_bold_text_with_bright_colors = true
primary = { background = "#0d0b07", foreground = "#c0c6cb" }
cursor = { text = "CellBackground", cursor = "CellForeground" }
selection = { text = "CellBackground", cursor = "CellForeground" }
[colors.normal]
black = "#0d0b07"
red = "#877B7D"
green = "#3F5E82"
yellow = "#527191"
blue = "#65798C"
magenta = "#6A86A0"
cyan = "#799EC2"
white = "#c0c6cb"
[colors.bright]
black = "#868a8e"
red = "#877B7D"
green = "#3F5E82"
yellow = "#527191"
blue = "#65798C"
magenta = "#6A86A0"
cyan = "#799EC2"
white = "#c0c6cb"

