[colors]
draw_bold_text_with_bright_colors = true
primary = { background = "#1E1E2E", foreground = "#CDD6F4", dim_foreground = "#CDD6F4", bright_foreground = "#CDD6F4" }
cursor = { text = "CellBackground", cursor = "CellForeground" }
selection = { text = "CellBackground" , cursor = "CellForeground" }
indexed_colors = [
    { index = 16, color = "#FAB387" },
    { index = 17, color = "#F5E0DC" }
]
[colors.normal]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"
[colors.bright]
black = "#585B70"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A6ADC8"
[colors.dim]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"
