theme = "ayu_dark"

[editor]
mouse = false
line-number = "relative"
cursorline = true
scrolloff = 8
scroll-lines = 5
color-modes = true
auto-save = true
bufferline = "multiple"
completion-trigger-len = 3

[editor.file-picker]
hidden = false

[editor.search]
smart-case = true
wrap-around = true

[editor.lsp]
display-messages = true
display-signature-help-docs = false
display-inlay-hints = true



################################################################################
###   APPEARANCE
################################################################################

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.whitespace.characters]
space = "·"
tab = "→"
tabpad = "·"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"



################################################################################
###   STATUS LINE
################################################################################

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator", "version-control"]
center = []
right = ["file-encoding", "file-type", "position", "diagnostics"]



################################################################################
###   KEYMAPS
################################################################################

[keys.normal]
y = { y = ["extend_line_below", "yank"] }  # yy to yank the entire line.
C-s = ":w"
"up" = "jump_view_up"
"left" = "jump_view_left"
"down" = "jump_view_down"
"right" = "jump_view_right"
